### PR TITLE
Lay out the node with stabby and read decorations without unsafe

### PR DESCRIPTION
**Pull request by martijnarts**
A `DecoratedNode` carried a reference to the host's `DecorationMap`. A plugin walked that map with code it compiled on its own. The map is a hash table, and only one compiler defines how std lays one out. The plugin also cast each value it found, and only a key comparison made that cast sound.

This pull request removes both reads. The host seals its entries into one list, with a sorted list of positions into it. A `DecorationLookup` carries the two lists as stabby slices, and the plugin searches them itself. The lookup is `Copy` and four words wide, so a node still carries one.

Each decoration sits in a stabby `Any` box. A read compares the stored type's identity and its layout report against the requested type, and returns `None` when they differ. A key that names another type now gives a wrong answer instead of a wrong read. `Decoration` is therefore a safe trait, and a rule author no longer discharges a safety obligation.

stabby lays out the node itself. The tree-sitter node inside is a C struct that stabby cannot see into. A `StableLike` carries it beside a copy of that struct's layout, and the compiler checks the copy for size and alignment. That read is the one unsafe operation left in the path, because `tree_sitter::Node` does not implement `IStable`. The decoration path held 39 mentions of `unsafe` across four files, and it now holds that one.

The boundary fingerprint names only the types that a pass receives and returns. The tree, the decoration map, and the coverage types never crossed, so they no longer contribute. A change to one of them no longer refuses every published plugin.

The rules repository is pinned to a commit that builds against this change, so that whisker's check of itself loads its rules. That commit pins the `abi/node-lookup-pin` branch. Both pins move to the release that carries the change.

Part of https://github.com/aonyx-ai/whisker/issues/343.

### CODE REVIEW

File: crates/whisker-types/src/decorated_node.rs [hunk 1]
```diff
@@ -136,48 +170,49 @@ impl<'a> DecoratedNode<'a> {
...
+///
+/// `value` must have come back from a lookup under `T::KEY`. The host
+/// stored it under that key, and the [`Decoration`] contract makes a key
+/// name exactly one type definition. That `T` is laid out the same in
+/// both images rests on two things. `T` is `IStable`, and the language
+/// fingerprint refuses a plugin whose decoration types differ from the
+/// host's.
+unsafe fn cast<T: Decoration>(value: &()) -> &T {
+    unsafe { &*ptr::from_ref(value).cast::<T>() }
+}
```
[the remark this answers is not in the document]
Comment (martijnarts) [reply crates/whisker-types/src/decorated_node.rs]: Rewritten. `cast` now takes a `NonNull<()>` and builds `&'a T` from it; nothing routes through a reference to a ZST any more.

File: crates/whisker-types/src/decoration_lookup.rs [hunk 2]
```diff
@@ -0,0 +1,206 @@
...
+/// The handle is `Copy`, because a [`DecoratedNode`] is, and it holds two
+/// words: the pointer and the function.
+///
+/// [`DecoratedNode`]: crate::DecoratedNode
+#[stabby::stabby]
+#[derive(Copy, Clone)]
+pub struct DecorationLookup<'a> {
+    map: &'a (),
+    read: unsafe extern "C" fn(&'a (), usize, DecorationKey, usize) -> Option<&'a ()>,
+}
```
[the remark this answers is not in the document]
Comment (martijnarts) [reply crates/whisker-types/src/decoration_lookup.rs:24]: Rewritten. The handle holds a `NonNull<()>` and carries the borrow in a `PhantomData<&'a DecorationMap>`. `read` takes a `NonNull<()>` and returns `Option<NonNull<()>>`, which keeps the null niche across the boundary. `Send` and `Sync` are implemented by hand, with the reasoning in the type doc.

File: crates/whisker-types/src/decoration_map.rs [hunk 3]
```diff
@@ -86,6 +86,15 @@ impl ErasedValue {
...
     }
+
+    /// Returns the stored value as a pointer to nothing
+    ///
+    /// A reference to `()` asks only that the address is not null. The
+    /// pointer to the boxed value satisfies that for as long as this entry
+    /// lives.
+    fn erased(&self) -> &() {
+        unsafe { self.ptr.as_ref() }
+    }
```
[the remark this answers is not in the document]
Comment (martijnarts) [reply crates/whisker-types/src/decoration_map.rs]: Rewritten. `erased` returns the `NonNull<()>` the entry already holds, and the plugin side is the only place that makes a reference out of it.

File: crates/whisker-types/src/decorated_node.rs [hunk 4]
```diff
@@ -31,93 +45,113 @@ impl<'a> DecoratedNode<'a> {
...
 
     /// Retrieves all decorations of type `T` from this node
     pub fn decorations_of_type<T: Decoration>(&self) -> Vec<&'a T> {
-        self.decorations.get_all::<T>(self.node.id())
+        let mut found = Vec::new();
+        while let Some(value) = self.decorations.get(self.id(), T::KEY, found.len()) {
+            found.push(unsafe { cast::<T>(value) });
+        }
+
+        found
```
[the remark this answers is not in the document]
Comment (martijnarts) [reply crates/whisker-types/src/decorated_node.rs]: Left as is, deliberately. The rescan is over one node's entries, not the map. A node carries a handful of decorations, and the repeated ones come in ones and twos. A cursor would add a second `usize` and an out-parameter to the boundary to save a few key comparisons per node. If a decoration ever fans out, grouping entries per key on the host side fixes it without touching the ABI.

File: crates/whisker-types/src/decoration_lookup.rs [hunk 5]
```diff
@@ -0,0 +1,222 @@
...
+#[stabby::stabby]
+#[derive(Copy, Clone)]
+pub struct DecorationLookup<'a> {
+    map: NonNull<()>,
+    read: unsafe extern "C" fn(NonNull<()>, usize, DecorationKey, usize) -> Option<NonNull<()>>,
+    borrow: PhantomData<&'a DecorationMap>,
+}
+
+unsafe impl Send for DecorationLookup<'_> {}
+unsafe impl Sync for DecorationLookup<'_> {}
```
[the remark this answers is not in the document]
Comment (martijnarts) [reply crates/whisker-types/src/decoration_lookup.rs]: Done. A `const _` block calls a `const fn` bounded on `Send + Sync` with `DecorationMap`, so a map that loses either fails to compile next to the two implementations.

File: crates/whisker-types/src/decoration_lookup.rs [hunk 6]
```diff
@@ -0,0 +1,232 @@
...
+/// disguise, and the map is `Send` and `Sync`, so the handle is whatever
+/// `&DecorationMap` is.
+///
+/// [`DecoratedNode`]: crate::DecoratedNode
+#[stabby::stabby]
+#[derive(Copy, Clone)]
+pub struct DecorationLookup<'a> {
+    map: NonNull<()>,
+    read: unsafe extern "C" fn(NonNull<()>, usize, DecorationKey, usize) -> Option<NonNull<()>>,
+    borrow: PhantomData<&'a DecorationMap>,
```
[the remark this answers is not in the document]
Comment (martijnarts) [reply crates/whisker-types/src/decoration_lookup.rs]: Left as is. `Option<NonNull<T>>` is one of the layouts Rust guarantees: the reference's type-layout chapter states that `Option<NonNull<T>>` has the same size, alignment, and function-call ABI as `*mut T`, with `None` as the null pointer. That guarantee is what makes the signature FFI-safe, and rustc's `improper_ctypes_definitions` lint agrees, which is why the crate compiles under `-D warnings`. stabby checks the same thing from its side: both types are `IStable` and carry the null niche in their reports. A raw pointer with a null check on the Rust side would say the same thing with one more way to get it wrong.

File: crates/whisker-types/src/decorated_node.rs [hunk 7]
```diff
@@ -31,93 +45,113 @@ impl<'a> DecoratedNode<'a> {
...
+            ..*self
+        }
+    }
+
     /// Returns the tree-sitter node kind (e.g. `"function_item"`)
-    pub fn kind(&self) -> &str {
-        self.node.kind()
+    pub fn kind(&self) -> &'a str {
+        self.inner().kind()
     }
```
[the remark this answers is not in the document]
Comment (martijnarts) [reply crates/whisker-types/src/decorated_node.rs:76]: Left as is. `tree_sitter::Node::kind` returns `&'static str`, so `'a` is a loosening, not a constraint: the previous `&str` was tied to `&self`, and `inner()` now hands out the node by value, so a borrow of `self` would have nothing to point into. A caller that held a `&str` from `self` can hold the `&'a str` for at least as long.

File: crates/whisker-types/src/ts_node.rs [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+///
+/// The type is public because stabby names it in the layout it records
+/// for [`DecoratedNode`]. Its module is not, so nothing outside this crate
+/// can name it.
+///
+/// [`DecoratedNode`]: crate::DecoratedNode
+/// [`StableLike`]: stabby::abi::StableLike
+/// [`StableLike::new`]: stabby::abi::StableLike::new
+#[stabby::stabby]
+pub struct TsNode {
```
[the remark this answers is not in the document]
Comment (martijnarts) [reply crates/whisker-types/src/ts_node.rs:25]: Left as is, because `pub(crate)` does not compile: `#[stabby::stabby]` on `DecoratedNode` generates public items that name the wrapper's type, and rustc refuses a crate-private type in a public interface (E0446, six errors). `unreachable_pub` is allow-by-default and not among the lints this repository enables, which is why CI passes under `-D warnings`.

File: crates/whisker-types/src/decoration_lookup.rs [hunk 9]
```diff
@@ -0,0 +1,232 @@
...
+    /// # Examples
+    ///
+    /// ```
+    /// use whisker_types::{DecorationLookup, DecorationMap};
+    ///
+    /// let map = DecorationMap::new();
+    ///
+    /// let lookup = DecorationLookup::of(&map);
+    ///
+    /// let copy = lookup;
```
[the remark this answers is not in the document]
Comment (martijnarts) [reply crates/whisker-types/src/decoration_lookup.rs]: Done. The binding is `_copy`.

**Comment by martijnarts** [comment]
@comment-quality review

File: crates/whisker-types/src/decoration_lookup.rs [hunk 10]
```diff
@@ -0,0 +1,232 @@
...
+
+/// Pins the fact the two implementations above rest on
+///
+/// A map that stopped being `Send` or `Sync` would not stop the handle
+/// from claiming both, because a hand-written implementation overrides
+/// the compiler's judgment. This fails to compile instead.
+const _: () = {
+    const fn shared<T: Send + Sync>() {}
+    shared::<DecorationMap>();
+};
```
Comment (martijnarts) [inline crates/whisker-types/src/decoration_lookup.rs]: should this not be in tests?

File: crates/whisker-types/src/decoration_lookup.rs [hunk 11]
```diff
@@ -0,0 +1,232 @@
...
+/// neither. The handle is a shared borrow of a [`DecorationMap`] in
+/// disguise, and the map is `Send` and `Sync`, so the handle is whatever
+/// `&DecorationMap` is.
+///
+/// [`DecoratedNode`]: crate::DecoratedNode
+#[stabby::stabby]
+#[derive(Copy, Clone)]
+pub struct DecorationLookup<'a> {
+    map: NonNull<()>,
+    read: unsafe extern "C" fn(NonNull<()>, usize, DecorationKey, usize) -> Option<NonNull<()>>,
```
Comment (martijnarts) [inline crates/whisker-types/src/decoration_lookup.rs]: I think there's a clippy lint requiring safety comments for `unsafe`s? enable that and write safety comments.

this is not exposed is it?

**Review by martijnarts — COMMENTED** [review]
maybe have Fable burn some tokens on thinking/researching methods to not use unsafe here if at all possible...

File: crates/whisker-types/src/decoration_lookup.rs (hunk 11 above)
Comment (martijnarts) [reply crates/whisker-types/src/decoration_lookup.rs]: `DecorationLookup` is exposed: `pub use decoration_lookup::DecorationLookup` in whisker-types' `lib.rs`. It has to be, because it is a field of `DecoratedNode`, which stabby lays out publicly.

On the lint: `clippy::undocumented_unsafe_blocks` is off today. There are 51 unsafe sites across 12 files and no SAFETY comments anywhere, and most of those files are ones this stack never touches. Enabling it at the bottom of the stack would put several hundred lines of comments into that commit, across whisker-macros, `decoration.rs`, `decorated_tree.rs` and `custom_lints.rs`.

So it goes in a separate pull request on top of the stack. This stack documents the unsafe it introduces, and that PR enables the lint and documents the rest.

One thing that PR has to settle: the lint wants `// SAFETY:` on the block, and `CLAUDE.md` says no inline comments, doc comments only. The carve-out belongs in the same change as the lint.

File: crates/whisker-types/src/decoration_lookup.rs (hunk 10 above)
Comment (martijnarts) [reply crates/whisker-types/src/decoration_lookup.rs]: The `const _` block is gone, along with the two implementations it guarded.

The handle no longer holds a raw pointer, so it no longer needs a hand-written `Send` and `Sync`. It is two `stabby::slice::Slice`s now, and those carry both traits by where-clause. There is nothing left to assert, so the question of where the assertion belongs does not arise.

File: crates/whisker-types/src/decoration_lookup.rs (hunk 11 above)
Comment (martijnarts) [reply crates/whisker-types/src/decoration_lookup.rs]: Fable took the research. The short version: the lookup path reaches one `unsafe` site, and that one is forced.

The design it found removes the raw pointer and the host callback. The host seals its entries into one list with a sorted index, the handle carries both as stabby slices, and the plugin searches them itself. Each decoration sits in a stabby `Any` box, so reading one back is `stable_downcast_ref`, which compares the stored type's identity and its layout report before it casts. That check is what let `Decoration` stop being an unsafe trait: a key that names the wrong type now costs a lookup its answer, not its soundness.

The path held 39 mentions of `unsafe` across four files. It now holds one: `DecoratedNode::inner`, which reads the `tree_sitter::Node` out of its `StableLike` wrapper. That one is forced, and the proof is short. `tree_sitter::Node` is `#[repr(transparent)]` over `TSNode` and does not implement `IStable`; stabby's checked accessor is gated on `IStable`; tree-sitter's only reconstruction is `unsafe fn from_raw`; and writing `unsafe impl IStable for Node` by hand is itself an unsafe site. Three routes, one site each.

The `extern "C"` surface went the same way, in https://github.com/aonyx-ai/whisker/pull/365. Six sites became two: the declaration's `load` field and the function it points at. That is the floor as well, because after `dlopen` the host holds an address and a name and no stabby value, so something must be called before any vtable exists.

One correction to what I said earlier in this thread. Removing `extern "C"` does not remove a `Panic::catch`. The hazard is two panic runtimes, not the calling convention, so the catch count tracks how many entry points run plugin code.

https://github.com/aonyx-ai/whisker/pull/371 turns on `clippy::undocumented_unsafe_blocks` and writes the comment for the site that remains.
